################################################################################
# Base image
################################################################################

FROM php:5.4-fpm

################################################################################
# Environment variables
################################################################################

ENV LOCALTIME Europe/Munich
ENV PHPFPM__access.format '"%R - %u [%t] \"%m %r\" %s %l %Q %f"'

################################################################################
# Build instructions
################################################################################

# COPY conf/apt.conf /etc/apt/apt.conf.d/

################################################################################
# Arguments
################################################################################

# ARG http_proxy
# ARG https_proxy

# Install PHP packages
RUN apt-get update && \
    apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        libgmp-dev \
        libxml2-dev \
        zlib1g-dev \
        libncurses5-dev \
        libldap2-dev \
        libssh2-1-dev \
        libicu-dev \
        libmemcached-dev \
        libcurl4-openssl-dev \
        libssl-dev \
        php-pear \
        curl \
        ssmtp \
        mysql-client \
        git \
        subversion \
        wget && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/include/gmp.h && \
    docker-php-ext-install pdo && \
    docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd && \
    docker-php-ext-install pdo_mysql && \
    docker-php-ext-configure mysql --with-mysql=mysqlnd && \
    docker-php-ext-install mysql && \
    docker-php-ext-configure mysqli --with-mysqli=mysqlnd && \
    docker-php-ext-install mysqli && \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/lib && \
    docker-php-ext-install gd && \
    docker-php-ext-install mcrypt && \
    docker-php-ext-install bcmath && \
    docker-php-ext-install mbstring && \
    docker-php-ext-install soap && \
    docker-php-ext-install zip && \
    docker-php-ext-install pcntl && \
    docker-php-ext-install ftp && \
    docker-php-ext-install xml && \
    pecl install hash && \
    pecl install ssh2-0.13 && \
    pecl install memcached-2.2.0 && \
    pecl install xdebug-2.4.1

RUN echo 'sendmail_path = /usr/sbin/ssmtp -t' >> $PHP_INI_DIR/conf.d/00-default.ini && \
    echo "\ninclude=/usr/local/etc/php-fpm.d/*.conf" >> /usr/local/etc/php-fpm.conf && \
    mkdir -p /usr/local/etc/php-fpm.d && \
    chmod a+w -R $PHP_INI_DIR/conf.d/ /etc/ssmtp /usr/local/etc/php-fpm.d

WORKDIR /var/www

################################################################################
# Volumes
################################################################################

# VOLUME []

################################################################################
# Ports
################################################################################

# EXPOSE 80 443

################################################################################
# Entrypoint
################################################################################

COPY conf/docker-entrypoint-5.4.sh /entrypoint.sh
COPY conf/php.ini $PHP_INI_DIR/conf.d/40-user.ini

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php-fpm"]
