version: '3'
services:
    php7.1:
        build:
            context: .
            dockerfile: Dockerfile-7.1
        links:
            - mysql
            - memcached
            - redis
        volumes:
            - ./www:/var/www/html

    php5.4:
        build:
            context: .
            dockerfile: Dockerfile-5.4
        links:
            - mysql
            - memcached
            - redis
        volumes:
            - ./www:/var/www/html
        tty: true

    web:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./www:/var/www/html
            - ./sites:/etc/nginx/conf.d
            - ./ssl:/etc/nginx/ssl
        links:
            - php7.1
            - php5.4

    mysql:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./conf/my.cnf:/etc/mysql/conf.d/my_custom.cnf
        environment:
            MYSQL_ROOT_PASSWORD: Alexandru90

    memcached:
        image: memcached:alpine

    redis:
        image: redis:alpine
