version: '3'
services:
    php:
        build:
            context: .
            args:
                - http_proxy=${http_proxy}
                - https_proxy=${https_proxy}
        links:
            - mysql
            - memcached
            - redis
        volumes:
            - ./www:/var/www/html

    web:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./www:/var/www/html
            - ./sites:/etc/nginx/conf.d
        links:
            - php

    # php:
    #     image: php:7-fpm
    #     volumes:
    #         - ./www:/var/www/html

    mysql:
        image: mysql
        ports:
            - "5003:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: Alexandru90

    memcached:
        image: memcached
        ports:
            - "5004:11211"

    redis:
        image: redis
        ports:
            - "5005:6379"
