version: '3'
services:
    php7.1:
        container_name: php7.1
        build:
            context: .
            dockerfile: Dockerfile-7.1
        links:
            - mysql
            - memcached
            - redis
        volumes:
            - ./www:/var/www/html

    php5.4:
        container_name: php5.4
        build:
            context: .
            dockerfile: Dockerfile-5.4
        links:
            - mysql
            - memcached
            - redis
        ports:
            - 8080:80
            - 8081:443
        volumes:
            - ./www:/var/www/html
        environment:
            PHP_php5enmod: 'xdebug intl'
            HTTPD__DocumentRoot: '/var/www/html/one2move-old'
            HTTPD__DirectoryIndex: 'index.php'
            HTTPD_a2enmod: 'access_compat alias auth_basic authn_core authn_file authz_core authz_host authz_user autoindex deflate dir env filter mime mpm_prefork negotiation php5 rewrite setenvif status'

    nginx:
        container_name: nginx
        image: nginx:alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./www:/var/www/html
            - ./sites:/etc/nginx/conf.d
            - ./ssl:/etc/nginx/ssl
        links:
            - php7.1
            - php5.4

    mysql:
        container_name: mysql
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./conf/my.cnf:/etc/mysql/conf.d/my_custom.cnf
        environment:
            MYSQL_ROOT_PASSWORD: Alexandru90

    memcached:
        container_name: memcached
        image: memcached:alpine

    redis:
        container_name: redis
        image: redis:alpine
